labels:
  title_label: "Schooltuinen Amsterdam Roostermaker"
  sub_title: Amsterdamse Schooltuinen X ADC - Collective Week 2025
  instructions: "Gebruiksaanwijzing programma"
  # subheader_label: "*** Uitleg voor gebruik ***"
  Beschikbaarheid_educatief_medewerkers: |
      Beschikbaarheid educatief medewerkers

  Beschikbaarheid_educatief_medewerkers_tekst: |
    Dit bestand bevat de beschikbaarheid van alle educatief medewerkers voor alle mogelijke lesmomenten en tuinen. De volgende codes kunnen per lesmoment worden ingevuld:
    <br><br>

    * Een <strong><span style="color: #2682FF;">B</span></strong> betekent dat de educatief medewerker <strong><span style="color: #2682FF;">beschikbaar</span></strong> is.  
    * Een <strong><span style="color: #2682FF;">N</span></strong> betekent dat de educatief medewerkers <strong><span style="color: #2682FF;">niet beschikbaar</span></strong> is.  
    * Een <strong><span style="color: #2682FF;">O</span></strong> betekent dat de educatief medewerkers <strong><span style="color: #2682FF;">onderhoud</span></strong> heeft.  
    * Een <strong><span style="color: #2682FF;">V</span></strong> betekent dat de educatief medewerker <strong><span style="color: #2682FF;">voorwaardelijk beschikbaar</span></strong> is.<br>  
    Wanneer meerdere lesmomenten met een <strong><span style="color: #2682FF;">V</span></strong> zijn ingevuld, wordt de educatief medewerker op een van die lesmomenten niet ingeroosterd. De overige lesmomenten met een <strong><span style="color: #2682FF;">V</span></strong> blijven beschikbaar voor eventuele indeling.

  Beschikbaarheid_groepen: |
      Beschikbaarheid groepen
  Beschikbaarheid_groepen_tekst: 
    Dit bestand bevat de beschikbaarheid van alle groepen voor specifieke tuinen. De data komt uit de ingevulde forms met daarin de voorkeuren voor lesmomenten en dagen.
  Schooltuinen_informatie: Schooltuinen informatie
  Schooltuinen_informatie_tekst: Dit bestand bevat alle informatie over de tuinen, zoals het maximale aantal groepen en bussen per lesmoment en het aantal reservetuintjes. 
  Upload_files: "Upload bestanden"
  stap_2: "**Stap 2.** Klik op '_Draai Programma_' en wacht tot de '_Klaar met optimalisatie_' tekst en de resultaten verschijnen. De resultaten laten informatie over de optimilisatie zien, zoals bijvoorbeeld hoeveel groepen niet zijn ingedeeld per tuin."
  stap_3: "**Stap 3.** Download geoptimaliseerd rooster door op '_Download Resultaten_' te klikken."
  educators_label: "Beschikbaarheid medewerkers"
  school_label: "Beschikbaarheid groepen"
  garden_label: "Schooltuinen informatie"
  run_label: "Maak rooster"
  finished_run_label: "Klaar met optimalisatie!"
test:
  test_sub: 1
  test_sub_2: hello
etl:
  school:
    primary_keys: 
      - "period_id"
      - "school_id"
      - "garden_name"
    col_mapping:
      - "code": code
      - "periodeid": period_id
      - "schoolcode": school_id
      - "naam": name
      - "lopenofbus": transport_type
      - "telefoon": phone
      - "tuinlocatie": garden_name
      - "groepniveauvan": group_level
      - "groep": group
      - "leerlingen": students
      - "voorkeursperiode": preferred_period
      - "opmerkingen": comments
      - "SO boeken / Engels": special_education_books
      - "vrijveld1": num_groups_from_school
      - "vrijveld2": preference_1
      - "vrijveld3": preference_2
      - "vrijveld4": preference_3
      - "vrijveld5": preference_4
      - "vrijveld6": preference_5
      - "locatie": location
    col_names_to_check_duplicates:
      - schoolcode
      - naam
      - groep
    col_names_timeslots:
      - preference_1
      - preference_2
      - preference_3
      - preference_4
      - preference_5
  educator:
    primary_keys: 
      - "garden_name"
      - "educator"
    col_mapping:
      - "Tuinlocatie": "garden_name"
      - "Medewerker": "educator"
  garden:
    primary_keys: 
      - "garden_name"
    col_mapping:
      - "Tuinlocatie": "garden_name"
      - "Aantal beschikbare tuintjes": "available_plots"
      - "Maximaal aantal groepen per tijdslot": "max_groups_per_timeslot"
      - "Maximaal aantal bussen per tijdslot": "max_buses_per_timeslot"
      - "Aantal reserve tuintjes": "reserved_plots"
validations:
  # - test_validation:
  #     optional: True
  #     df: school_data
  #     key_cols: 
  #       - "period_id"
  #       - "school_id"
  #       - "garden_name"
  # - test_validation:
  #     optional: True
  #     df: educator_data
  #     key_cols: 
  #       - "garden_name"
  #       - "educator"
  # - test_validation:
  #     optional: True
  #     df: garden_data
  #     key_cols: 
  #       - "garden_name"
  - check_any_empty_cols:
      optional: False
      df: educator_data
  - check_duplicates:
      optional: False
      df: school_data
      col_names_to_check_duplicates: 
        - "school_id"
        - "name"
        - "group"
  - check_key_cols:
      optional: False
      df: school_data
      key_cols: 
        - "period_id"
        - "school_id"
        - "garden_name"
  - check_key_cols:
      optional: False
      df: educator_data
      key_cols: 
        - "garden_name"
        - "educator"
  - check_key_cols:
      optional: False
      df: garden_data
      key_cols: 
        - "garden_name"
  - confirm_key_exists_and_is_identical:
      optional: False
      key_col: garden_name
      df_1: garden_data
      df_2: school_data
  - check_at_least_one_col_filled:
      optional: True
      df: school_data
      cols:
        - "preference_1"
        - "preference_2"
        - "preference_3"
        - "preference_4"
        - "preference_5" 
      group_id_col: period_id
template_file_names:
  "educators_template": "Template educators.xlsx"
  "school_template": "PLACEHOLDER Template schools.xlsx"
  "garden_template": "Template school garden.xlsx"      
Styles:
 css: |
    .header {
          font-size: 60px;
          font-weight: bold;
          text-align: center;
          width: 100%;
          padding: 10;  
          display: flex;
          justify-content: center;  
          white-space: nowrap;  
          color: #17254F;    
          }
          .subheader {
          font-size: 28px;
          color: #666;
          #text-align: center;
          width: auto;
          padding: 10;   
          white-space: nowrap;
          color: #5C6169; 
          }
          .title {
    font-size: 30px; /* Kleinere tekst */
    #text-align: left; /* Links uitlijnen */
    width: auto; /* Past zich aan de tekst aan */
    padding: 0px;  
    display: block; /* Geen flex nodig */
    white-space: normal; /* Regels kunnen afbreken indien nodig */
    color: #17254F
        }
        .subtitle {
        font-size: 24px; /* Kleinere tekst */
        font-weight: 600;
    #text-align: left; /* Links uitlijnen */
    width: auto; /* Past zich aan de tekst aan */
    padding: 0px;  
    display: block; /* Geen flex nodig */
    white-space: normal; /* Regels kunnen afbreken indien nodig */
    color: #17254F
    }
        .text {
        font-size: 18px; /* Kleinere tekst */
    #text-align: left; /* Links uitlijnen */
    width: auto; /* Past zich aan de tekst aan */
    padding: 0px;  
    display: block; /* Geen flex nodig */
    white-space: normal; /* Regels kunnen afbreken indien nodig */
    color: #5C6169; 
      }
          .text_red {
        font-size: 18px; /* Kleinere tekst */
    #text-align: left; /* Links uitlijnen */
    width: auto; /* Past zich aan de tekst aan */
    padding: 0px;  
    display: block; /* Geen flex nodig */
    white-space: normal; /* Regels kunnen afbreken indien nodig */
    color: #E32636; 
      }
