labels:
  title_label: "Goede morgen!"
  educators_label: "Leraren Beschikbaarheid Data"
  school_label: Groep Beschikbaarheid Data"
  garden_label: "Schooltuinen Data"
  run_label: "Run!!!"
test:
  test_sub: 1
  test_sub_2: hello
etl:
  school:
    primary_keys: 
      - "period_id"
      - "school_code"
    col_mapping:
      - "code": code
      - "periodeid": period_id
      - "schoolcode": school_code
      - "naam": name
      - "lopenofbus": transport_type
      - "telefoon": phone
      - "tuinlocatie": garden_name
      - "groepniveauvan": group_level
      - "groep": group
      - "leerlingen": students
      - "voorkeursperiode": preferred_period
      - "opmerkingen": comments
      - "SO boeken / Engels": special_education_books
      - "vrijveld1": num_groups_from_school
      - "vrijveld2": preference_1
      - "vrijveld3": preference_2
      - "vrijveld4": preference_3
      - "vrijveld5": preference_4
      - "vrijveld6": preference_5
      - "locatie": location
    col_names_timeslots:
      - preference_1
      - preference_2
      - preference_3
      - preference_4
      - preference_5
  educator:
    primary_keys: 
      - "garden_name"
      - "medewerker"
    col_mapping:
      - "Tuinlocatie": "garden_name"
      - "Medewerker": "educator"
  garden:
    primary_keys: 
      - "garden_name"
    col_mapping:
      - "Tuinlocatie": "garden_name"
      - "Aantal beschikbare tuintjes": "available_plots"
      - "Maximaal aantal groepen per tijdslot": "max_groups_per_timeslot"
      - "Maximaal aantal bussen per tijdslot": "max_buses_per_timeslot"
      - "Aantal reserve tuintjes": "reserved_plots"
validations:
  # check_duplicates:
  #   df: school_df
  #   col_names_to_check_duplicates: 
  #     - "school_code"
  #     - "name"
  #     - "group"
  #   sort_by_col: "period_id"
  # confirm_key_exists_and_is_identical:
  #   key_col: garden_name
  #   df_1: garden_df
  #   df_2: school_df
    